"""add giveaways

Revision ID: 1c1100da6c4
Revises: 594305e616b
Create Date: 2014-12-22 00:20:12.366696

"""

# revision identifiers, used by Alembic.
revision = '1c1100da6c4'
down_revision = '594305e616b'

from alembic import op
import sqlalchemy as sa


t_from = sa.Enum('valid', 'invalid', 'finished')
t_to   = sa.Enum('valid', 'invalid', 'finished', 'giveaway')


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('giveaway_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###
    op.alter_column('trade', 'status', type_=t_to, existing_type=t_from)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'giveaway_count')
    ### end Alembic commands ###
    op.alter_column('trade', 'status', type_=t_from, existing_type=t_to)
