"""empty message

Revision ID: 24adefb2a8d
Revises: 4772352bbff
Create Date: 2014-07-26 21:50:39.289466

"""

# revision identifiers, used by Alembic.
revision = '24adefb2a8d'
down_revision = '4772352bbff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('status', sa.Enum('valid', 'invalid', 'finished', 'deleted'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'status')
    ### end Alembic commands ###
