"""empty message

Revision ID: 4169d11408
Revises: 24adefb2a8d
Create Date: 2014-07-27 16:03:02.842732

"""

# revision identifiers, used by Alembic.
revision = '4169d11408'
down_revision = '24adefb2a8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('trade', sa.Column('finalized', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'finalized')
    op.drop_column('trade', 'created')
    ### end Alembic commands ###
