"""empty message

Revision ID: 4772352bbff
Revises: 483e7fd9289
Create Date: 2014-07-26 16:07:05.965587

"""

# revision identifiers, used by Alembic.
revision = '4772352bbff'
down_revision = '483e7fd9289'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('creator_flair_css', sa.String(length=64), nullable=True))
    op.add_column('trade', sa.Column('target_flair_css', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'target_flair_css')
    op.drop_column('trade', 'creator_flair_css')
    ### end Alembic commands ###
