"""empty message

Revision ID: 483e7fd9289
Revises: None
Create Date: 2014-07-26 14:56:22.713768

"""

# revision identifiers, used by Alembic.
revision = '483e7fd9289'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('creator', sa.String(length=32), nullable=True),
    sa.Column('creator_flair', sa.String(length=256), nullable=True),
    sa.Column('target', sa.String(length=32), nullable=True),
    sa.Column('target_flair', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    ### end Alembic commands ###
