"""add ip columns

Revision ID: 594305e616b
Revises: 9a3542295c
Create Date: 2014-08-07 11:51:23.840723

"""

# revision identifiers, used by Alembic.
revision = '594305e616b'
down_revision = '9a3542295c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('creator_ip', sa.String(length=64), nullable=True))
    op.add_column('trade', sa.Column('target_ip', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'target_ip')
    op.drop_column('trade', 'creator_ip')
    ### end Alembic commands ###
